import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css"


export const metadata = {
  title: "Dieudonné",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <head>
      <link
      rel="shortcut icon"
      href="./images/icon-dev.svg"
      type="image/x-icon"
    />
      </head>
      <body
        className={`antialiased`}
      >
        <div className="w-full bg-white px-4 md:px-8 lg:px-16 xl:px-32 2xl:px-64">
        </div>
        
         {children}
       </body>
     </html>
  );
}
